# simple dockerfile to test OCP s2i using Dockerfile 

#FROM ubuntu:18.04
FROM openshift4/ose-cli:latest
#CMD ["/bin/bash", "-c", "sleep infinity"]
CMD ["/bin/bash", "-c", "--", "while true; do sleep 30; done;"]
