# simple dockerfile to test OCP s2i using Dockerfile 

#FROM ubuntu:18.04
FROM openshift/ose-base:v4.10.0.20220421.121857
#CMD ["/bin/bash", "-c", "sleep infinity"]
CMD ["/bin/bash", "-c", "--", "while true; do sleep 30; done;"]
